POST {{ host}} /auth/signup
Content-Type: application/json

{
  "name": "Mao",
  "email": "Mao@Test.com",
  "password": "test1234",
  "phone": "010-1234-5678"
}
###

POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "Mao@Test.com",
  "password": "test1234"
}

###