POST {{host}}/api/v1/auth/signup
Content-Type: application/json

{
  "email": "Mao@Test.com",
  "memberName": "Mao",
  "password": "test1234",
  "nickName": "010-1234-5678"
}

###

POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "Mao@Test.com",
  "password": "test1234"
}

###