# 회원가입 요청
POST {{host}}/api/v1/auth/signup
Content-Type: application/json

{
  "email": "Mao@Test.com",
  "memberName": "Mao",
  "password": "test1234",
  "nickName": "010-1234-5678"
}

###

# 로그인 요청
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "Mao@Test.com",
  "password": "test1234"
}

> {%
  client.test("Request executed successfully", function() {
    var accessToken = response.headers['AccessToken'] ;
    if (accessToken) {
      client.global.set("jwt_token", accessToken.split(' ')[1]);
    }
  });
  client.log(response.headers["Vary"]);
%}