### JWT 토큰을 이용한 게시글 등록 요청
POST {{host}}/api/v1/post
Content-Type: application/json
AccessToken: Bearer {{jwt_token}}

{
  "title": "Test Title",
  "contents": "Test Contents"
}
> {%
 client.test("Request executed successfully", function (){
   var responseBody = JSON.parse(response.body);
   var postToken = responseBody.data.postToken;
   if (postToken) {
     client.global.set("postToken", postToken);
   }
 });
%}
###

# Fetch a post by token
GET {{host}}/api/v1/post/fetch/{{postToken}}
Content-Type: application/json

###

# Fetch all posts
GET {{host}}/api/v1/post/fetch
Content-Type: application/json

###

# Update a post
PUT {{host}}/api/v1/post/{{postToken}}
Content-Type: application/json
AccessToken: Bearer {{jwt_token}}

{
  "title": "Updated Title1",
  "contents": "Updated Contents"
}

###

# Delete a post
DELETE {{host}}/api/v1/post/{{postToken}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}