version: "3"
services:
  server:
    container_name: concurrency-example-backend-server-local
    image: concurrency-example-backend-server-local:latest
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PROFILE=local
      - PORT=8080
      - TZ=Asia/Seoul