name : Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: SSH 접속
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_DEV_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          envs: APPLICATION_DEV_PROPERTIES
          script_stop: true
          script: |
            cd /home/ubuntu/concurrencyPrac
            rm -rf scr/main/resources/application.yml
            git pull origin master
            echo "APPLICATION_DEV_PROPERTIES" > src/main/resources/application-dev.yml
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &


