name : test GA

on:
  push:
    branches:
      - master

jobs:
  Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Code Hello World
        run: echo "Hello World"

      - name: 여러문장
        run: |
          echo "Hi"
          echo "Hello"

      - name: 자체 변수
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
